import 'server-only'

import { createClient, type SupabaseClient } from '@supabase/supabase-js'

let client: SupabaseClient | null = null

/**
 * Supabase client with `service_role`: **bypasses RLS**. Only for the fixed
 * charges cron and the webhook's writes (ARCHITECTURE.md §2).
 *
 * The `server-only` import breaks the build if this module ends up in a
 * client bundle: with this key exposed, anyone can read and write everyone's
 * expenses. The env vars are read inside the function, not at module scope,
 * so they come from the runtime environment.
 */
export function supabaseAdmin(): SupabaseClient {
  if (client) return client

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceRole = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!url || !serviceRole) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
  }

  // TODO: type the client with the types generated by `supabase gen types`
  // once the schema is applied in the project.
  client = createClient(url, serviceRole, {
    auth: { persistSession: false, autoRefreshToken: false },
  })

  return client
}
